### ISSUE TITLE
Milestone 4 - Finish Dash app R

### ISSUE THREAD

**Issue by nobbynguyen** [UBC-MDS/netviz-R#1]
- Put together all the code our team members created for IA2 in an DashR @liannah @y248guo 
- Update your README with a link to the deployed R dashboard and a new image/gif of the R dashboard in action. @lynnwbl 
- Include the link to your deployed dashboard clearly visible near the top of your README or in the ABOUT section of the repo. @lynnwbl

**Comment by lynnwbl** [comment]
Trending plot: https://github.com/lynnwbl/532-IA2-heroku

**Comment by nobbynguyen** [comment]
Please paste the link to your IA2 repo in this issue.

**Comment by y248guo** [comment]
Table of examples https://github.com/y248guo/netflix_dashR_app

**Comment by nobbynguyen** [comment]
bar chart: https://github.com/nobbynguyen/basic_dash-Rapp

**Comment by liannah** [comment]
https://github.com/liannah/map_netflix - map
